### PR TITLE
Improvement/app view styles

### PR DESCRIPTION
**Pull request by ruig1992**
[trs Upgrade application styles](https://trello.com/c/3bjCuryD)

**ATTENTION!** This PR contains many application style updates! There may be conflicts with other PRs.

### CODE REVIEW

**Comment by TatsuUkraine** [comment]
@ruig1992 resolve conflicts

**Comment by ruig1992** [comment]
@TatsuUkraine  Conflicts resolved.

**Comment by TatsuUkraine** [comment]
@ruig1992 resolve conflicts

**Comment by ruig1992** [comment]
@TatsuUkraine  Conflicts resolved.

**Review by TatsuUkraine — APPROVED** [review]

**Pull request merged**
